# -*- mode: ruby -*-

NET="192.168.10."
DOMAIN="local"

servers = [
  {
    :hostname => "server1." + DOMAIN,
    :ip => NET + "11",
    :ssh_host => "2211",
    :ssh_vm => "22",
    :ram => 1024,
    :core => 1,
    :hdd_name => "server1_hdd.vdi",
    :hdd_size => "10240"
  },
  {
    :hostname => "server2." + DOMAIN,
    :ip => NET + "12",
    :ssh_host => "2212",
    :ssh_vm => "22",
    :ram => 1024,
    :core => 1,
    :hdd_name => "server2_hdd.vdi",
    :hdd_size => "10240"
  },
  {
    :hostname => "server3." + DOMAIN,
    :ip => NET + "13",
    :ssh_host => "2213",
    :ssh_vm => "22",
    :ram => 1024,
    :core => 1,
    :hdd_name => "server3_hdd.vdi",
    :hdd_size => "10240"
  }
]

Vagrant.configure(2) do |config|
    config.vm.synced_folder ".", "/vagrant", disabled: true
    servers.each do |machine|
        config.vm.define machine[:hostname] do |node|
            node.vm.box = "debian/jessie64"
            node.vm.usable_port_range = (2200..2250)
            node.vm.hostname = machine[:hostname]
            node.vm.network "private_network", ip: machine[:ip]
            node.vm.network :forwarded_port, guest: machine[:ssh_vm], host: machine[:ssh_host]
            node.vm.provider "virtualbox" do |vb|
                vb.customize ["modifyvm", :id, "--memory", machine[:ram]]
                vb.customize ["modifyvm", :id, "--cpus", machine[:core]]
                vb.name = machine[:hostname]
                if (!machine[:hdd_name].nil?)
                    unless File.exist?(machine[:hdd_name])
                        vb.customize ["createhd", "--filename", machine[:hdd_name], "--size", machine[:hdd_size]]
                    end
                    vb.customize ["storageattach", :id, "--storagectl", "SATA Controller", "--port", 1, "--device", 0, "--type", "hdd", "--medium", machine[:hdd_name]]
                end
            end
        end
        config.vm.provision "shell" do |s|
          ssh_pub_key = File.expand_path("~#{ENV['USER']}/.ssh/id_rsa.pub")
          s.inline = <<-SHELL
            echo #{ssh_pub_key} >> /home/vagrant/.ssh/authorized_keys
            SHELL
        end
        config.vm.provision "ansible" do |setup|
          setup.inventory_path = "../ansible/hosts"
          setup.playbook = "../ansible/roles/setup.yaml"
          setup.become = true
          setup.extra_vars = { ansible_user: 'vagrant' }
        end
    end
end
