# -*- mode: ruby -*-

nodes = {
  "node1" => "192.168.10.10",
  "node2" => "192.168.10.20",
  "node3" => "192.168.10.30"
}

Vagrant.configure("2") do |config|
  config.vm.box = "debian/jessie64"
  config.vm.box_url = "debian/jessie64"
  nodes.each do |name, ip|
    config.vm.define name do |machine|
      machine.vm.hostname = "%s" % name
      machine.vm.network :private_network, ip: ip
      machine.vm.provider "virtualbox" do |v|
        v.customize ["modifyvm", :id, "--memory", 1024]
        v.customize ["modifyvm", :id, "--cpus", 1]
      end
    end
    config.vm.provision "ansible" do |setup|
      setup.playbook = "../ansible/roles/setup.yaml"
      setup.become = true
      setup.extra_vars = { ansible_user: 'vagrant' }
    end
  end
end
