- name: Initialize Swarm Master
 hosts: swarm-master
 gather_facts: yes
 sudo: true
 tasks:
 - command: "docker swarm init --advertise-addr eth0"
 - command: "docker swarm join-token -q worker"
 register: swarm_token
 - set_fact: swarmtoken="{{swarm_token.stdout}}"

- name: Join Swarm Nodes
 hosts: swarm-nodes
 gather_facts: yes
 sudo: true
 tasks:
 - command: "docker swarm join \
           --advertise-addr eth0 \
           --token {{hostvars[groups['swarm-master'][0]].swarmtoken}} {{hostvars[groups['swarm-master'][0]].inventory_hostname}}:2377"
